---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cm2metric
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cm2metric-configmap-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cm2metric
subjects:
- kind: ServiceAccount
  name: default
  namespace: cm2metric
  
---
apiVersion: v1
kind: Namespace
metadata:
  name: cm2metric
  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cm2metric
  name: cm2metric
  namespace: cm2metric
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: cm2metric
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm2metric
  labels:
    app: cm2metric
    namespace: cm2metric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm2metric
  template:
    metadata:
      labels:
        app: cm2metric
    spec:
      containers:
      - name: cm2metric
        image: docker.pkg.github.com/aserhat/cm2metric/cm2metric:v0.2.0
