---
kind: ConfigMap
apiVersion: v1
metadata:
  name: c2m-certificate-expiration
  namespace: cm2metric
  labels:
    prom_metric: certificate_expiration
    prom_description: "The_certificate_phase"
    prom_labels: "certificate"
data:
  apiserver: "1"
